### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by BenMKT** [MustafaSamiShirzad/portfoliowebsite2#4]
- Great work on the project however kindly check below suggestions:
- For the page width cropping bug, please add a `min-width` property with `fit-content` value to your `body` element in the desktop media query version to fix this issue.
- Import the font weight for the google fonts to resolve the bug.

**Comment by MustafaSamiShirzad** [comment]
thanks for your reviews but i have already solved them
